### ISSUE TITLE
Error calling GetRoomParameters 

### ISSUE THREAD

**Issue by R00iBaard** [Onotseike/Xamarin-WebRTC-Tutorial#7]
Hi there,

Thanks so much for the project. I am getting the following error after I select Start Call after entering a GUID.

> Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher[8]
      Failed to invoke hub method 'GetRoomParametersAsync'.
System.InvalidOperationException: Cannot access child value on Newtonsoft.Json.Linq.JValue.
   at Newtonsoft.Json.Linq.JToken.get_Item(Object key)
   at WebRTC.Signalling.Server.Models.Complex.TURNClient.RequestServersAsync() in C:\Synap\Development\Xamarin-WebRTC-Tutorial\WebRTC.Signalling.Server\Models\Complex\TURNClient.cs:line 61
   at WebRTC.Signalling.Server.Hubs.WebRTCHub.GetRoomParametersAsync(String _roomId, Boolean _isInitiator, String _turnBaseUrl) in C:\Synap\Development\Xamarin-WebRTC-Tutorial\WebRTC.Signalling.Server\Hubs\WebRTCHub.cs:line 397
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.ExecuteHubMethod(ObjectMethodExecutor methodExecutor, THub hub, Object[] arguments)
   at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.<>c__DisplayClass13_0.<<Invoke>g__ExecuteInvocation|0>d.MoveNext()

**Comment by R00iBaard** [comment]
I see var serversObject = iceServersJson["iceServers"]; 
is missing - {"v":"unauthorized","s":"error"} on the API call auth https://global.xirsys.net/_turn/DemoWebRTC

**Comment by Onotseike** [comment]
> I see var serversObject = iceServersJson["iceServers"]; 
> 
> is missing - {"v":"unauthorized","s":"error"} on the API call auth https://global.xirsys.net/_turn/DemoWebRTC

Hi @R00iBaard, this is because you need to supply your own credentials. Which can be done by creating an account with Xirsys and creating an app registration which will provide you with the said credentials. This is the link to the relevant Xirsys documentation for credentials [https://docs.xirsys.com/?pg=using-portal](https://docs.xirsys.com/?pg=using-portal)

**Comment by R00iBaard** [comment]
Great that makes sense sorry. If I would love to achieve this locally only (will explain below) can this be done without needing IceServers/Turn etc?

We have an edge case where we would love to share video local only ("hole punching" I think its called) where both devices will not have an internet connection (in a mine). I am aware that peers can run peer to peer but the initial handshaking with the signaling server where its deployed on a server somewhere. Is there a better technology for this scenario other than WebRTC maybe? We went down the road with Ant Media server, works perfectly, however, the server can only run on ubuntu.

The broadcaster is an android device written in Java
The player is a Xamarin forms application. Maybe its possible to run the signalling server directly within the xamarin mobile app?

**Comment by Onotseike** [comment]
Hi @R00iBaard i believe in theory it could be possible to run a signalling server on an android device. However, that would be costly in terms of computing power and battery for the device. Also you might need to implement this with websockets.
